### PR TITLE
Task1 works as expected

### PR DESCRIPTION
**Pull request by AndriyGalias**
## Describe your changes
The script is designed to work as expected.
Users can easily run this script by navigating to the directory where the script is stored.
The script will prompt users to enter the path to the folder they want to check and specify the file extension.

To run this script, use the following command:
./task1.sh

Please make sure you are in the directory where the script is located before executing the command.

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [ ] If it is a core feature, I have added thorough tests.
- [ ] Do we need to implement analytics?
- [x] Will this be part of a product update? If yes, please write one phrase about this update.

### CODE REVIEW

**Comment by AndriyGalias** [comment]
Consider enhancing the code with additional validation and provide feedback or suggestions for any existing errors.

**Review by sbodia — APPROVED** [review]

**Comment by dnason** [comment]
Looks reasonable.

**Comment by dnason** [comment]
Looks reasonable.

**Review by dnason — APPROVED** [review]
Looks reasonable!

**Review by arkma — APPROVED** [review]

**Pull request merged**
